[build]
  command = "npm install && npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"

# Handle trailing slashes (Next.js export uses them)
[[redirects]]
  from = "/tools"
  to = "/tools/"
  status = 301

[[redirects]]
  from = "/tools/waterways-assistant"
  to = "/tools/waterways-assistant/"
  status = 301

[[redirects]]
  from = "/tools/elevation"
  to = "/tools/elevation/"
  status = 301

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"