global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'default'
  routes:
    - match:
        severity: critical
      receiver: 'critical'
      repeat_interval: 15m
    - match:
        severity: warning
      receiver: 'warning'
      repeat_interval: 4h

receivers:
  - name: 'default'
    # Configure your default notification method here
    # Example: webhook, email, slack, etc.

  - name: 'critical'
    # Configure critical alert notifications
    # Example: PagerDuty, SMS, phone call

  - name: 'warning'
    # Configure warning alert notifications
    # Example: Slack, email

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'cluster', 'service']